language: node.js
node_js:
  - "stable"
dist: trusty
sudo: required

branches:
  only:
    - master

before_script:
  - npm i -g @angular/cli

script
- ng lint
- npm run test-headless
- ng build --prod --base-href https://marynaageeva.github.io/CI-test/
